---
- hosts: default
  vars:
    pipeline_script: "{{ lookup('file', 'files/Jenkinsfile') }}"
  # roles:
  #   - name: roles/jenkins
  #     vars:
  #       jenkins_plugins:
  #         - blueocean
  #         - git
  #         - job-dsl
  #         - workflow-aggregator
  #     become: yes
  tasks:
    - name: 'load secrets'
      include_vars:
        file: 'files/secrets.yml'    
    # - name: make Jenkins home directory
    #   file:
    #     path: '/home/jenkins'
    #     owner: 'jenkins'
    #     group: 'jenkins'
    #     state: 'directory'
    #   become: yes

    # - name: copy files
    #   copy:
    #     src: "files/{{ item }}"
    #     dest: "/home/jenkins/{{ item }}"
    #     mode: 0755
    #   with_items:
    #     - 'certificate.sh'
    #     - 'msg.txt'
    #   become: yes
    #   become_user: 'jenkins'

    # - name: 'pipeline config'
    #   template:
    #     src: 'files/job.xml.j2'
    #     dest: '/home/jenkins/job.xml'
    #   become: yes
    #   become_user: 'jenkins'
    
    # - name: 'create demo pipeline job'
    #   jenkins_job:
    #     name: 'Pipeline Demo 2'
    #     config: "{{ lookup('file', '/home/jenkins/job.xml') }}" # "{{ lookup('file', 'files/job.xml') }}"
    #     url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    #     user: "{{ jenkins_admin_username }}"
    #     password: "{{ jenkins_admin_password }}"
    
    # - name: 'configure mutt' # requires "smtp_pass" to be set to the jenkinsboothCGI@gmail.com password
    #   template:
    #     src: 'files/muttrc.j2'
    #     dest: '/home/jenkins/.muttrc'
    #     owner: 'jenkins'
    #     group: 'jenkins'
    #     mode: 700
    #   become: yes

    - name: 'download demo WAR source code'
      get_url:
        url: 'https://bwa.nrs.gov.bc.ca/int/stash/rest/archive/latest/projects/NPE/repos/npe-e2edemo-war/archive?at=refs%2Fheads%2Ffeature%2Fxml-config&format=zip'
        url_username: "{{ stash_username }}"
        url_password: "{{ stash_password }}"
        dest: '/tmp/npe-e2edemo-war.zip'
      become: yes
      become_user: 'jenkins'
    
    - name: 'npe-e2edemo-war folder'
      file:
        path: '/home/jenkins/npe-e2edemo-war'
        state: directory
        mode: 0700
      become: yes
      become_user: 'jenkins'
    
    - name: 'extract source code'
      unarchive:
        src: '/tmp/npe-e2edemo-war.zip'
        remote_src: yes
        dest: '/home/jenkins/npe-e2edemo-war'
      become: yes
      become_user: 'jenkins'